### ISSUE TITLE
Suggestion: allow script to be silent

### ISSUE THREAD

**Issue by slicer69** [kvechera/kill_descendants#1]
I have a suggestion for future versions of this script. Since kill_descendants might be used in a script, it would be useful to be able to make it silent, ie not have any output.

kill_descendants is very nice about returning a useful exit code for success, failure or child processes still running.

My suggestion is to add a quiet ("-q") flag so that no output is echoed. The script just returns its exit code without any output.

**Comment by kvechera** [comment]
Thanks for the suggestion. I've added the quiet mode.
